name = "Qprism"
uuid = "ea22d434-8a6a-4204-995b-559f0279a651"
authors = ["Jaewoo Joung <jaewoo.joung@consultant.volvo.com>"]
version = "1.0.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Cascadia = "54eefc05-d75b-58de-a785-1a3403f0919f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Gumbo = "708ec375-b3d6-5a57-a7ce-8257bf98657a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
WebDriver = "05625dda-b54a-434a-8c43-5c7937dfa4f0"
SMTPClient = "80a5b449-b9dc-5cea-adf7-6c68e3d580ae"

[compat]
julia = "1.6"
AbstractTrees = "0.4"
Cascadia = "1"
Gumbo = "0.8"
HTTP = "1"
JSON3 = "1"
WebDriver = "0.2"
SMTPClient = "0.6"
